[package]
name = "calcxporteR"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
dirs = "6.0.0"
dotenv = "0.15.0"
resend-rs = "0.16.1"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
